/**
 * restaurant-data.ts
 *
 * THE single source of truth for all restaurant content.
 * - `RestaurantData` is the canonical type for every field.
 * - `defaultRestaurantData` is the seed — the live site is pixel-identical
 *   when this is unmodified.
 * - At runtime, the CMS reads from data/restaurant.json (if it exists) and deep-merges
 *   with these defaults so new fields are always forward-compatible.
 *
 * OPERATOR NOTE: To reset a deployed site to defaults, delete data/restaurant.json.
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export type MenuItem = {
  name: string;
  desc?: string;
  price: string;
  veg?: boolean;
  star?: boolean;
};

export type MenuCategory = {
  id: string;
  label: string;
  items: MenuItem[];
};

export type SignatureDish = {
  name: string;
  tag: string;
  price: string;
  img: string;
  veg: boolean;
};

export type Review = {
  text: string;
  who: string;
};

export type GalleryPhoto = {
  src: string;
  cat: "ambience" | "food" | "drinks" | "food_drinks" | "party";
  caption: string;
};

export type Milestone = {
  year: string;
  title: string;
  body: string;
};

export type Stat = {
  n: string;
  l: string;
};

export type SeoPageMeta = {
  title: string;
  description: string;
  ogImage?: string;
};

export type RestaurantData = {
  // ── Identity ──────────────────────────────────────────────────────────────
  name: string;
  tagline: string;
  logoUrl: string;
  loadingSubtext?: string;   // e.g. "warming up the grill..."
  foundedYear: string;

  // ── Contact ───────────────────────────────────────────────────────────────
  address: string;           // Full address for contact page
  addressShort: string;      // Abbreviated for footer
  phone: string;             // Display format e.g. "+91 99997 39766"
  whatsappNumber: string;    // Digits only e.g. "919999739766" for wa.me links
  hours: string;             // e.g. "10:00 am – 10:30 pm every day"
  hoursShort: string;        // e.g. "Open daily · 10 AM – 10:30 PM"
  priceRange: string;        // e.g. "Approx ₹400–900 for two · cards & UPI accepted"

  // ── Social / Maps ─────────────────────────────────────────────────────────
  socialLinks: {
    instagram: string;
    maps: string;
  };
  mapsEmbedQuery: string;    // Query string for Google Maps embed src

  // ── Hero (homepage) ───────────────────────────────────────────────────────
  heroLocationBadge: string; // e.g. "Satya Niketan · open till 10:30 PM"
  heroHeadline: [string, string, string]; // 3 lines; line[1] gets coral colour, line[2] gets marker-underline
  heroHeadlineSince: string; // The "since YEAR" script annotation on h1
  heroSubcopy: string;
  heroStats: string[];       // Small stat pills below CTA buttons
  heroStats: string[];       // Small stat pills below CTA buttons
  heroCollagePhotos: [string, string]; // 2 collage photo URLs
  heroCollageAlts: [string, string];
  heroCollageAnnotation: string; // Handwritten annotation on the collage

  // ── Marquee ───────────────────────────────────────────────────────────────
  marqueeItems: string[];
  marqueeDishes?: string[];  // 5 custom dish names displayed on the moving bar

  // ── Story teaser (homepage section) ───────────────────────────────────────
  storyTeaserPhoto: string;
  storyTeaserPhotoAlt: string;
  storyTeaserScriptLabel: string;
  storyTeaserPrefix?: string;      // e.g. "Eleven years of"
  storyTeaserH2: [string, string]; // [normal part, coral/highlighted part]
  storyTeaserBody: string;

  // ── About page ────────────────────────────────────────────────────────────
  milestones: Milestone[];
  stats: Stat[];
  pressQuote: string;
  pressAttribution: string;

  // ── Menu ──────────────────────────────────────────────────────────────────
  menu: MenuCategory[];

  // ── Signature dishes (homepage) ───────────────────────────────────────────
  signatureDishes: SignatureDish[];

  // ── Reviews ───────────────────────────────────────────────────────────────
  reviews: Review[];

  // ── Gallery ───────────────────────────────────────────────────────────────
  galleryPhotos: GalleryPhoto[];
  homepageGalleryPhotos?: string[]; // 10 featured showcase photos for homepage & gallery "Everything"

  // ── Footer ────────────────────────────────────────────────────────────────
  footerTagline: string;   // e.g. "since 2014"
  footerBody: string;      // Paragraph under the name/tagline

  // ── SEO meta per page ─────────────────────────────────────────────────────
  seoMeta: {
    home: SeoPageMeta;
    menu: SeoPageMeta;
    about: SeoPageMeta;
    contact: SeoPageMeta;
    gallery: SeoPageMeta;
  };

  // ── CMS lock ──────────────────────────────────────────────────────────────
  isLocked: boolean;
  autoGeneratedFields?: string[];
};

// ─── Seed defaults ───────────────────────────────────────────────

export const defaultRestaurantData: RestaurantData = {
  // Identity
  name: "The Litup Cafe",
  tagline: "Good Food, Great Vibes & Unforgettable Nights",
  logoUrl: "/logo.png",
  loadingSubtext: "turning on the neon lights...",
  foundedYear: "2018",

  // Contact
  address: "Hudson Lane, GTB Nagar, New Delhi, Delhi",
  addressShort: "Hudson Lane, GTB Nagar\nNew Delhi, Delhi",
  phone: "+91 79824 88464",
  whatsappNumber: "917982488464",
  hours: "11:00 am – 11:30 pm every day",
  hoursShort: "Open daily · 11 AM – 11:30 PM",
  priceRange: "Approx ₹600–1000 for two",

  // Social
  socialLinks: {
    instagram: "https://www.instagram.com/the_lit_up_cafe",
    maps: "https://maps.app.goo.gl/XHPYdb7Dx3HgtegWA",
  },
  mapsEmbedQuery: "The+Litup+Cafe+Hudson+Lane",

  // Hero
  heroLocationBadge: "Hudson Lane · open till 11:30 PM",
  heroHeadline: ["Cozy vibes.", "Great food.", "Neon nights."],
  heroHeadlineSince: "since 2018",
  heroSubcopy:
    "Located in the heart of Hudson Lane, The Litup Cafe is your ultimate destination for mouth-watering dishes, signature mocktails, and a vibrant, neon-lit atmosphere perfect for parties and casual hangouts.",
  heroStats: [],
  heroCollagePhotos: [
    "/photos/photo_57.jpeg", 
    "/photos/photo_17.jpeg",
  ],
  heroCollageAlts: [
    "Creamy Pasta", 
    "Stuffed Garlic Bread Sticks",
  ],
  heroCollageAnnotation: "Good times!",

  // Marquee
  marqueeItems: [
    "HUDSON LANE'S FINEST",
    "LIVE DJ WEEKENDS",
    "SIGNATURE MOCKTAILS",
    "CRAZY GOOD PIZZA",
  ],
  marqueeDishes: [
    "Kadhai Paneer",
    "Honey Chilli Potato",
    "Roasted Chicken Sizzler",
    "The Litup Pizza",
    "Signature Mocktail",
  ],

  // Story teaser
  storyTeaserPhoto: "/photos/img4.jpg",
  storyTeaserPhotoAlt: "Red velvet lounge seating at The Litup Cafe",
  storyTeaserScriptLabel: "the story so far",
  storyTeaserPrefix: "Years of",
  storyTeaserH2: ["memorable", "nights out."],
  storyTeaserBody:
    "We started with a simple idea: bring great food and incredible vibes together under neon lights. The Litup Cafe is the spot to gather your friends, enjoy massive sizzlers, and make memories in Hudson Lane.",

  // About page
  milestones: [
    {
      year: "2018",
      title: "Opening Doors",
      body: "We launched in Hudson Lane with a vision for neon vibes.",
    },
    {
      year: "2020",
      title: "Surviving the pause",
      body: "Delivering our signature momos and pasta straight to your doors.",
    },
    {
      year: "2022",
      title: "The Big Upgrade",
      body: "Redesigned our interiors with plush seating and neon signs.",
    },
  ],
  stats: [
    { n: "10K+", l: "Happy Guests" },
    { n: "60+", l: "Menu Items" },
    { n: "1", l: "Amazing Location" },
  ],
  pressQuote: "The best new spot for amazing mocktails and cozy vibes in GTB Nagar.",
  pressAttribution: "Hudson Lane Reviewer",

  menu: [
    {
      id: "soups",
      label: "Soups",
      items: [
        { name: "Tomato Soup", desc: "", price: "199", veg: true },
        { name: "Mix Veg Soup", desc: "", price: "199", veg: true },
        { name: "Sweet Corn Soup", desc: "", price: "199", veg: true },
        { name: "Cream of Mushroom", desc: "", price: "269", veg: true },
        { name: "Munchow Soup", desc: "", price: "199", veg: true },
        { name: "Veg Hot Soup", desc: "", price: "199", veg: true },
        { name: "Chicken Munchow Soup", desc: "", price: "249", veg: false },
        { name: "Lemon and Coriander Soup", desc: "", price: "249", veg: false },
        { name: "Hot and Sour Soup", desc: "", price: "249", veg: false },
      ]
    },
    {
      id: "salad-peanut",
      label: "Salad & Peanut",
      items: [
        { name: "Green Salad", desc: "", price: "199", veg: true },
        { name: "Russian Salad", desc: "", price: "249", veg: true },
        { name: "Cucumber Salad", desc: "", price: "149", veg: true },
        { name: "Tandoori Salad", desc: "", price: "269", veg: true },
        { name: "Masala Pappad", desc: "", price: "199", veg: true },
        { name: "Masala Peanut", desc: "", price: "199", veg: true },
        { name: "Plain Peanut", desc: "", price: "99", veg: true },
      ]
    },
    {
      id: "chinese",
      label: "Chinese",
      items: [
        { name: "Chilli Potato", desc: "", price: "249", veg: true },
        { name: "Cheese Fries", desc: "", price: "349", veg: true },
        { name: "Honey Chilli Potato", desc: "", price: "279", veg: true },
        { name: "Peri-Peri French Fries", desc: "", price: "209", veg: true },
        { name: "Plain French Fries", desc: "", price: "199", veg: true },
        { name: "Manchurian Dry/Gravy", desc: "", price: "299/309", veg: true },
        { name: "Chilli Paneer Dry/Gravy", desc: "", price: "299/309", veg: true },
        { name: "Chilli Soya Chaap", desc: "", price: "299", veg: true },
        { name: "Salt & Pepper", desc: "", price: "299", veg: true },
        { name: "Potato Bites", desc: "", price: "299", veg: true },
        { name: "Peri-Peri Paneer Finger", desc: "", price: "309", veg: true },
        { name: "Crispy Paneer Finger Honey", desc: "", price: "299", veg: true },
        { name: "Chilli Mushroom", desc: "", price: "299", veg: true },
        { name: "Golden Fried Baby Corn", desc: "", price: "299", veg: true },
        { name: "Crispy Corn", desc: "", price: "229", veg: true },
        { name: "Fried Rice", desc: "", price: "299", veg: true },
        { name: "Spring Roll", desc: "", price: "279", veg: true },
        { name: "Chicken Fried Rice", desc: "", price: "299", veg: false },
        { name: "Chilli Chicken", desc: "", price: "349", veg: false },
        { name: "Lemon Chicken", desc: "", price: "349", veg: false },
        { name: "Chicken Lollipop", desc: "", price: "349", veg: false },
        { name: "Drums of Heaven", desc: "", price: "349", veg: false },
        { name: "Chicken 65", desc: "", price: "349", veg: false },
        { name: "Kung Pao Chicken", desc: "", price: "349", veg: false },
        { name: "Black Pepper Chicken", desc: "", price: "349", veg: false },
        { name: "Chicken Nuggets", desc: "", price: "349", veg: false },
      ]
    },
    {
      id: "noodles",
      label: "Noodles",
      items: [
        { name: "Veg Noodles", desc: "", price: "309", veg: true },
        { name: "Singapuri Noodles", desc: "", price: "309", veg: true },
        { name: "Hakka Noodles", desc: "", price: "299", veg: true },
        { name: "Chilli Garlic Noodles", desc: "", price: "299", veg: true },
        { name: "Chicken Noodles", desc: "", price: "329", veg: false },
        { name: "Chicken Egg Mix Noodles", desc: "", price: "379", veg: false },
        { name: "Egg Noodles", desc: "", price: "299", veg: false },
        { name: "Chicken Hakka Noodles", desc: "", price: "299", veg: false },
        { name: "Chicken Chilli Garlic Noodles", desc: "", price: "299", veg: false },
      ]
    },
    {
      id: "momos",
      label: "Momos",
      items: [
        { name: "Veg Momos (Steam/Fried)", desc: "", price: "189/199", veg: true },
        { name: "Paneer Momos (Steam/Fried)", desc: "", price: "199/219", veg: true },
        { name: "Chicken Momos (Steam/Fried)", desc: "", price: "249/269", veg: false },
        { name: "Tandoori Momos Add On", desc: "", price: "99", veg: true },
      ]
    },
    {
      id: "pasta",
      label: "Pasta",
      items: [
        { name: "Peri-Peri Pasta", desc: "Veg/Non-Veg", price: "309/379", veg: true },
        { name: "Arrabiata Pasta", desc: "Veg/Non-Veg", price: "309/379", veg: true },
        { name: "Alfredo Pasta", desc: "Veg/Non-Veg", price: "309/379", veg: true },
        { name: "Mix Sauce Pasta", desc: "Veg/Non-Veg", price: "309/379", veg: true },
        { name: "Makhni Pasta", desc: "Veg/Non-Veg", price: "309/349", veg: true },
        { name: "Pesto Sauce Pasta", desc: "Veg/Non-Veg", price: "309/349", veg: true },
        { name: "Mushroom Pasta", desc: "Veg/Non-Veg", price: "279/349", veg: true },
      ]
    },
    {
      id: "pizza",
      label: "Pizza",
      items: [
        { name: "Onion/Capsicum/Tomato Pizza", desc: "", price: "399", veg: true },
        { name: "Farmhouse Pizza", desc: "", price: "399", veg: true },
        { name: "Veg Surprise Pizza", desc: "", price: "399", veg: true },
        { name: "Mushroom Pizza", desc: "", price: "399", veg: true },
        { name: "Paneer Cheese Pizza", desc: "", price: "399", veg: true },
        { name: "Paneer Tikka Pizza", desc: "", price: "399", veg: true },
        { name: "Margherita Pizza", desc: "", price: "399", veg: true },
        { name: "Butter Chicken Pizza", desc: "", price: "449", veg: false },
        { name: "Chicken Cheese Pizza", desc: "", price: "449", veg: false },
        { name: "Chicken Tikka Pizza", desc: "", price: "449", veg: false },
        { name: "Chilli Chicken Pizza", desc: "", price: "449", veg: false },
        { name: "Spl. The Litup Pizza", desc: "", price: "449", veg: false },
      ]
    },
    {
      id: "garlic-bread",
      label: "Garlic Bread",
      items: [
        { name: "Plain Garlic Bread", desc: "", price: "199", veg: true },
        { name: "Cheese Garlic Bread", desc: "", price: "249", veg: true },
        { name: "Chilli Cheese Garlic Bread", desc: "", price: "299", veg: true },
        { name: "Paneer Cheese Garlic Bread", desc: "", price: "299", veg: true },
      ]
    },
    {
      id: "nachos-appetizers",
      label: "Nachos & Appetizers",
      items: [
        { name: "Plain Nachos", desc: "", price: "129", veg: true },
        { name: "Loaded Nachos", desc: "", price: "249", veg: true },
        { name: "Baked Cheese Nachos", desc: "", price: "299", veg: true },
        { name: "Cheese Balls", desc: "", price: "299", veg: true },
        { name: "Lasagna (Veg/Non-Veg)", desc: "", price: "449/649", veg: true },
      ]
    },
    {
      id: "sizzlers",
      label: "Sizzlers",
      items: [
        { name: "Paneer Tikka Sizzler", desc: "", price: "399", veg: true },
        { name: "Paneer Malai Tikka Sizzler", desc: "", price: "399", veg: true },
        { name: "Chilli Paneer Sizzler", desc: "", price: "399", veg: true },
        { name: "Chicken Tikka Sizzler", desc: "", price: "499", veg: false },
        { name: "Chilli Chicken Sizzler", desc: "", price: "499", veg: false },
        { name: "Chicken Malai Tikka Sizzler", desc: "", price: "499", veg: false },
      ]
    },
    {
      id: "roasted-tandoori",
      label: "Roasted/Tandoori",
      items: [
        { name: "Paneer Tikka", desc: "", price: "399", veg: true },
        { name: "Paneer Malai Tikka", desc: "", price: "399", veg: true },
        { name: "Tandoori Chaap", desc: "", price: "349", veg: true },
        { name: "Achari Chaap", desc: "", price: "349", veg: true },
        { name: "Achari Paneer Tikka", desc: "", price: "349", veg: true },
        { name: "Tandoori Mushroom", desc: "", price: "349", veg: true },
        { name: "Haryali Chaap", desc: "", price: "399", veg: true },
        { name: "Haryali Paneer Tikka", desc: "", price: "399", veg: true },
        { name: "Afghani Chaap", desc: "", price: "349", veg: true },
        { name: "Dahi Kebab", desc: "", price: "349", veg: true },
        { name: "Dahi Ke Sholay", desc: "", price: "349", veg: true },
        { name: "Stuffed Chaap", desc: "", price: "399", veg: true },
        { name: "Hara Bhara Kebab", desc: "", price: "349", veg: true },
        { name: "Veg Kurkure Chaap", desc: "", price: "399", veg: true },
        { name: "Tandoori Chicken", desc: "", price: "399", veg: false },
        { name: "Afghani Chicken", desc: "", price: "399", veg: false },
        { name: "Chicken Tikka", desc: "", price: "399", veg: false },
        { name: "Chicken Malai Tikka", desc: "", price: "399", veg: false },
        { name: "Banjara Chicken Tikka", desc: "", price: "399", veg: false },
        { name: "Peri-Peri Chicken Tikka", desc: "", price: "399", veg: false },
        { name: "Black Pepper Chicken Tikka", desc: "", price: "399", veg: false },
        { name: "Haryali Chicken Tikka", desc: "", price: "399", veg: false },
        { name: "Sharabi Chicken Tikka", desc: "", price: "449", veg: false },
        { name: "Chicken Seekh Kebab", desc: "", price: "399", veg: false },
        { name: "Punjabi Seekh Kebab", desc: "", price: "399", veg: false },
        { name: "Roasted Tangadi", desc: "", price: "499", veg: false },
        { name: "Mutton Seekh Kebab", desc: "", price: "499", veg: false },
      ]
    },
    {
      id: "main-course",
      label: "Main Course",
      items: [
        { name: "Kadhai Paneer", desc: "", price: "349", veg: true },
        { name: "Shahi Paneer", desc: "", price: "349", veg: true },
        { name: "Lababdar Paneer", desc: "", price: "379", veg: true },
        { name: "Mix Veg", desc: "", price: "309", veg: true },
        { name: "Dal Makhni", desc: "", price: "349", veg: true },
        { name: "Lahsooni Dal Tadka", desc: "", price: "349", veg: true },
        { name: "Paneer Butter Masala", desc: "", price: "349", veg: true },
        { name: "Paneer Do Pyaaza", desc: "", price: "349", veg: true },
        { name: "Palak Paneer", desc: "", price: "349", veg: true },
        { name: "Malai Kofta", desc: "", price: "349", veg: true },
        { name: "Dal Bukhara", desc: "", price: "349", veg: true },
        { name: "Tawa Chaap", desc: "", price: "329", veg: true },
        { name: "Aloo Jeera", desc: "", price: "249", veg: true },
        { name: "Seasonal Vegetables", desc: "", price: "249", veg: true },
        { name: "Aloo Gobhi", desc: "", price: "299", veg: true },
        { name: "Dum Aloo", desc: "", price: "299", veg: true },
        { name: "Butter Chicken", desc: "", price: "399", veg: false },
        { name: "Chicken Lababdar", desc: "", price: "399", veg: false },
        { name: "Kadhai Chicken", desc: "", price: "399", veg: false },
        { name: "Chicken Butter Masala", desc: "", price: "399", veg: false },
        { name: "Rara Chicken", desc: "", price: "399", veg: false },
        { name: "Punjabi Chicken", desc: "", price: "399", veg: false },
        { name: "Chicken Curry", desc: "", price: "399", veg: false },
        { name: "Mutton Rogan Josh", desc: "", price: "699", veg: false },
      ]
    },
    {
      id: "breads-rice",
      label: "Breads & Rice",
      items: [
        { name: "Plain Naan", desc: "", price: "75", veg: true },
        { name: "Tawa Roti", desc: "", price: "39", veg: true },
        { name: "Plain Roti", desc: "", price: "45", veg: true },
        { name: "Butter Roti", desc: "", price: "49", veg: true },
        { name: "Rumali Roti", desc: "", price: "45", veg: true },
        { name: "Laccha Parantha", desc: "", price: "75", veg: true },
        { name: "Butter Naan", desc: "", price: "79", veg: true },
        { name: "Butter Garlic Naan", desc: "", price: "79", veg: true },
        { name: "Stuffed Kulcha", desc: "", price: "99", veg: true },
        { name: "Amritsari Kulcha", desc: "", price: "99", veg: true },
        { name: "Veg Pulao", desc: "", price: "249", veg: true },
        { name: "Jeera Rice", desc: "", price: "239", veg: true },
        { name: "Kashmiri Rice", desc: "", price: "299", veg: true },
        { name: "Veg Biryani", desc: "", price: "299", veg: true },
        { name: "Plain Rice", desc: "", price: "199", veg: true },
        { name: "Chicken Biryani", desc: "", price: "399", veg: false },
      ]
    },
    {
      id: "raita",
      label: "Raita",
      items: [
        { name: "Mix Veg Raita", desc: "", price: "149", veg: true },
        { name: "Boondi Raita", desc: "", price: "119", veg: true },
        { name: "Plain Raita", desc: "", price: "99", veg: true },
      ]
    },
    {
      id: "platters",
      label: "Litup Special Platters",
      items: [
        { name: "Chinese Platter (Veg)", desc: "Fried Rice, Momos, Spring Roll, French Fries, Dry Manchurian", price: "399", veg: true },
        { name: "Tandoori Veg Platter", desc: "Paneer Tikka/Mushroom Tikka, Tandoori Momos, Chaap, Hara Bhara Kebab", price: "650", veg: true },
        { name: "Chinese Chicken Platter", desc: "Chicken Momos, Chicken Lollipop, Fried Rice, Chilli Chicken, French Fries", price: "499", veg: false },
        { name: "Tandoori Non-Veg Platter", desc: "Tandoori Chicken/Chicken Tikka, Chicken Seekh Kebab, Tandoori Chicken Momos, Chicken Malai Tikka", price: "750", veg: false },
      ]
    },
    {
      id: "mocktails",
      label: "Mocktails",
      items: [
        { name: "Blueberry Blast", desc: "", price: "279", veg: true },
        { name: "Fresh Lime Soda", desc: "", price: "199", veg: true },
        { name: "Sunrise", desc: "", price: "279", veg: true },
        { name: "Pink Iceland", desc: "", price: "279", veg: true },
        { name: "Lemonade Punch", desc: "", price: "279", veg: true },
        { name: "Virgin Mojito", desc: "", price: "279", veg: true },
        { name: "Green Apple Mojito", desc: "", price: "279", veg: true },
        { name: "Watermelon Mojito", desc: "", price: "279", veg: true },
        { name: "Kiwi Mojito", desc: "", price: "279", veg: true },
        { name: "X On The Beach", desc: "", price: "279", veg: true },
        { name: "Ice Tea", desc: "", price: "279", veg: true },
        { name: "Blue Lagoon", desc: "", price: "279", veg: true },
      ]
    },
    {
      id: "shakes",
      label: "Shakes",
      items: [
        { name: "Chocolate Monster", desc: "", price: "299", veg: true },
        { name: "Brownie Shake", desc: "", price: "299", veg: true },
        { name: "Ferrero Rocher Shake", desc: "", price: "299", veg: true },
        { name: "Oreo Shake", desc: "", price: "299", veg: true },
        { name: "Peanut Butter Shake", desc: "", price: "299", veg: true },
        { name: "Butterscotch Shake", desc: "", price: "299", veg: true },
        { name: "Naughty Nutella", desc: "", price: "299", veg: true },
        { name: "Strawberry Shake", desc: "", price: "299", veg: true },
        { name: "Blueberry Shake", desc: "", price: "299", veg: true },
        { name: "KitKat Shake", desc: "", price: "299", veg: true },
      ]
    },
    {
      id: "coffee",
      label: "Coffee",
      items: [
        { name: "Hot Coffee", desc: "", price: "199", veg: true },
        { name: "Cold Coffee", desc: "", price: "300", veg: true },
        { name: "Coffee Latte", desc: "", price: "300", veg: true },
        { name: "Coffee Espresso", desc: "", price: "300", veg: true },
      ]
    },
    {
      id: "desserts",
      label: "Desserts",
      items: [
        { name: "Brownie with Ice Cream", desc: "", price: "249", veg: true },
        { name: "Ice Cream (2 Scoop)", desc: "", price: "149", veg: true },
        { name: "Brownie Sizzler", desc: "", price: "349", veg: true },
        { name: "Gulab Jamun (2 Pieces)", desc: "", price: "199", veg: true },
        { name: "Ras Malai (2 Pieces)", desc: "", price: "199", veg: true },
        { name: "Hot Chocolate Brownie with Ice Cream", desc: "", price: "449", veg: true },
      ]
    },
    {
      id: "beverages",
      label: "Beverages",
      items: [
        { name: "Red Bull", desc: "", price: "275", veg: true },
        { name: "Coke/Limca/Fanta/Sprite Can", desc: "", price: "129", veg: true },
        { name: "Soda", desc: "", price: "99", veg: true },
        { name: "Mineral Water", desc: "", price: "49", veg: true },
        { name: "Real Mixed Fruit Juice (300ml)", desc: "", price: "249", veg: true },
        { name: "Real All Juice Flavours (300ml)", desc: "", price: "279", veg: true },
        { name: "Coke/Sprite Half Ltr.", desc: "", price: "149", veg: true },
        { name: "Tonic Water", desc: "", price: "129", veg: true },
        { name: "Ginger Ale", desc: "", price: "129", veg: true },
        { name: "Flavour Soda", desc: "", price: "130", veg: true },
        { name: "Champagne", desc: "", price: "1199", veg: true },
      ]
    },
  ],

  // Signature dishes (no prices shown — by design)
  signatureDishes: [
    {
      name: "Litup Special Platter",
      tag: "Fan Favourite",
      price: "",
      img: "/photos/photo_23.jpeg",
      veg: true,
    },
    {
      name: "Chicken Malai Tikka",
      tag: "Chef's Special",
      price: "",
      img: "/photos/photo_56.jpeg",
      veg: false,
    },
    {
      name: "Litup Sunset Cooler",
      tag: "Most Ordered",
      price: "",
      img: "/photos/photo_15.jpeg",
      veg: true,
    },
    {
      name: "Litup Sizzler Platter",
      tag: "House Special",
      price: "",
      img: "/photos/photo_20.jpeg",
      veg: false,
    },
  ],

  // Reviews — authentic Google reviews
  reviews: [
    { text: "Had a really great experience at Litup Cafe. The food quality was excellent — everything was fresh, tasty, and well presented. The ambience is very nice and cozy, making it a perfect place to relax and enjoy time with friends or family. One of the best things is that the cafe is budget-friendly, with good portion sizes and reasonable prices. Also, the staff was very polite, friendly, and attentive, which made the overall experience even better. Definitely a place worth visiting again!", who: "Mohd Areeb" },
    { text: "We hosted my husband's birthday party here and had an amazing time. All our friends enjoyed the scrumptious food and drinks. The service was also top notch. Thank you litup team for making it a memorable occasion. You guys are truly LITUP.", who: "Sumina Gupta" },
    { text: "The experience was great and the staff is very humble with me and I like the food also I had a amazing time here I'll be the loyal customer now thank you litup for this lovely experience here.", who: "Vishu Tanwar" },
    { text: "Another of the good places in GTB Nagar to hang out with your friends. Open all day. Perfect for birthday parties. The staff are friendly and the food is really good. Value for money.", who: "Abhijith Pillai" },
    { text: "Didn't have a dinner plan and stumbled onto this cafe while walking around. The crowd outside made it look worth trying. Went in, ordered the butter garlic naan and honey chilli potato. Both were really well made. The music was great and the whole vibe was much better than expected for a spontaneous stop.", who: "Priya Prakash" },
    { text: "Absolutely crispy spring rolls. KADAK. Meaning, they should sound so crispy while eating. The spring rolls at Litup have a crunch. My experience has been very good, especially the service here is very good, everyone serves them perfectly.", who: "Khushi Jaiswal" },
    { text: "Pure veg section here is massive and genuinely creative. Mushroom tikka, tandoori mushroom, haryali paneer, afghani chaap — they've really thought about giving vegetarians interesting options beyond standard paneer.", who: "Nazmin Khan" },
    { text: "You need a reliable place close to home where the food is good, the people are nice, and the prices are reasonable. If you live near North Campus, Litup is the place for you.", who: "Indu Mati" },
    { text: "One of the best cafe in North Delhi. Food quality and ambience excellent. Must visit cafe.", who: "Aas M" },
  ],

  // Gallery — food+drinks merged into food_drinks; party photos in own category
  galleryPhotos: [
    // food_drinks
    { src: "/photos/photo_12.jpeg", cat: "food_drinks", caption: "Sizzling Paneer Tikka Feast" },
    { src: "/photos/photo_14.jpeg", cat: "food_drinks", caption: "Stone-Baked Signature Pizza" },
    { src: "/photos/photo_15.jpeg", cat: "food_drinks", caption: "Signature Litup Sunset Cooler" },
    { src: "/photos/photo_16.jpeg", cat: "food_drinks", caption: "The Litup Special Pizza" },
    { src: "/photos/photo_20.jpeg", cat: "food_drinks", caption: "Litup Sizzler Platter" },
    { src: "/photos/photo_21.jpeg", cat: "food_drinks", caption: "Spicy Chicken Lollipop" },
    { src: "/photos/photo_23.jpeg", cat: "food_drinks", caption: "Special Chinese Platter" },
    { src: "/photos/photo_25.jpeg", cat: "food_drinks", caption: "Golden Cheese Balls & Paneer Tikka" },
    { src: "/photos/photo_26.jpeg", cat: "food_drinks", caption: "Creamy Malai Tikka" },
    { src: "/photos/photo_28.jpeg", cat: "food_drinks", caption: "Spicy Schezwan Noodles" },
    { src: "/photos/photo_30.jpeg", cat: "food_drinks", caption: "Classic Hakka Noodles" },
    { src: "/photos/photo_31.jpeg", cat: "food_drinks", caption: "Roasted Chicken Sizzler" },
    { src: "/photos/photo_32.jpeg", cat: "food_drinks", caption: "Thick Chocolate Oreo Shake" },
    { src: "/photos/photo_34.jpeg", cat: "food_drinks", caption: "Crispy Honey Chilli Potato" },
    { src: "/photos/photo_52.jpeg", cat: "food_drinks", caption: "Creamy White Sauce Pasta Platter" },
    { src: "/photos/photo_53.jpeg", cat: "food_drinks", caption: "Spicy Chicken Tikka" },
    { src: "/photos/photo_56.jpeg", cat: "food_drinks", caption: "Malai Chicken Tikka" },
    
    // ambience
    { src: "/photos/photo_01.jpeg", cat: "ambience", caption: "The Cozy Lounge Booth" },
    { src: "/photos/photo_02.jpeg", cat: "ambience", caption: "Neon Glow & Velvet Corners" },
    { src: "/photos/photo_03.jpeg", cat: "ambience", caption: "Litup Evening Atmosphere" },
    { src: "/photos/photo_06.jpeg", cat: "ambience", caption: "The Litup Bar Area" },
    { src: "/photos/photo_43.jpeg", cat: "ambience", caption: "Live DJ Console" },
    { src: "/photos/img1.jpg", cat: "ambience", caption: "Plush Velvet Seating" },
    { src: "/photos/img4.jpg", cat: "ambience", caption: "Relax & Unwind" },

    // party
    { src: "/photos/photo_08.jpeg", cat: "party", caption: "Birthday Decorations" },
    { src: "/photos/photo_10.jpeg", cat: "party", caption: "Party Vibes" },
    { src: "/photos/photo_36.jpeg", cat: "party", caption: "Birthday Celebrations" },
    { src: "/photos/photo_38.jpeg", cat: "party", caption: "Neon Party Lights" },
    { src: "/photos/party1.webp", cat: "party", caption: "Birthday Bash at Litup" },
    { src: "/photos/party2.webp", cat: "party", caption: "Celebration Nights" },
    { src: "/photos/party3.webp", cat: "party", caption: "Friends & Festivities" },
    { src: "/photos/party4.webp", cat: "party", caption: "Special Occasion Setup" },
    { src: "/photos/party5.webp", cat: "party", caption: "Party Crowd & Good Vibes" },
    { src: "/photos/party6.webp", cat: "party", caption: "DJ Night Weekend" },
    { src: "/photos/party7.webp", cat: "party", caption: "Table Decorations & Celebrations" },
    { src: "/photos/party8.webp", cat: "party", caption: "Group Celebration" },
    { src: "/photos/party9.webp", cat: "party", caption: "Litup Birthday Shoot" },
    { src: "/photos/party10.webp", cat: "party", caption: "Neon Lit Party" },
    { src: "/photos/party11.webp", cat: "party", caption: "Weekend Revelry" },
    { src: "/photos/party12.webp", cat: "party", caption: "Late Night Hang" },
  ],
  homepageGalleryPhotos: [
    "/photos/photo_20.jpeg",
    "/photos/photo_16.jpeg",
    "/photos/photo_01.jpeg",
    "/photos/photo_15.jpeg",
    "/photos/party1.webp",
    "/photos/photo_23.jpeg",
    "/photos/photo_06.jpeg",
    "/photos/photo_52.jpeg",
    "/photos/photo_38.jpeg",
    "/photos/photo_32.jpeg",
  ],


  // Footer
  footerTagline: "Good vibes since 2018",
  footerBody: "Gather your friends, enjoy massive sizzlers, and make memories in Hudson Lane under the neon lights.",

  // SEO
  seoMeta: {
    home: { title: "The Litup Cafe - Hudson Lane", description: "Good Food, Great Vibes" },
    menu: { title: "Menu | The Litup Cafe", description: "Explore our menu" },
    about: { title: "About Us | The Litup Cafe", description: "Our story" },
    contact: { title: "Contact | The Litup Cafe", description: "Get in touch" },
    gallery: { title: "Gallery | The Litup Cafe", description: "See our vibe" },
  },

  isLocked: false,
};

/**
 * Normalizes any Google Maps input (full embed URL, <iframe> snippet, place search query, or maps link)
 * into a valid, safe iframe src URL.
 */
export function getGoogleMapsEmbedUrl(queryOrUrl?: string): string {
  if (!queryOrUrl || !queryOrUrl.trim()) {
    return "https://www.google.com/maps?q=The+Litup+Cafe+Hudson+Lane&output=embed";
  }
  const trimmed = queryOrUrl.trim();

  // If a full <iframe> snippet was pasted (e.g. from Google Maps "Embed a map")
  const iframeMatch = trimmed.match(/src=["']([^"']+)["']/i);
  if (iframeMatch && iframeMatch[1]) {
    return iframeMatch[1];
  }

  // If already a Google Maps embed URL
  if (trimmed.includes("google.com/maps/embed")) {
    return trimmed;
  }

  // If already an embed query
  if (trimmed.includes("output=embed")) {
    return trimmed;
  }

  // If it's a URL or search text, construct standard embed
  return `https://www.google.com/maps?q=${encodeURIComponent(trimmed)}&output=embed`;
}
